version: '3.5'

volumes:
    db-data:

networks:
    default:
        external:
            name: hackathon

services:
    app:
        image: fshigueru/front
        container_name: ${PROJECT_NAME}_app
        env_file: .env
        restart: always
        volumes:
            - "./src:/src"
        ports:
            - "3000:3000"
            - "8084:8080"
            - "8085:80"
            - "35729:35729"
            - "1601:1601"